[tool.poetry]
name = "dw-core"
version = "0.0.0"
description = "Downwind Core"
authors = ["Guto Maia <guto@guto.net>"]

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.11.4"

[tool.poetry.group.dev.dependencies]
bandit = "^1.8.3"
git-changelog = "^2.4.1"
m2r = "^0.3.1"
pytest = "^8.3.5"
pytest-cov = "^6.1.1"
pytest-watch = "^4.2.0"
sphinx-autodoc-typehints = "^3.2.0"
sphinx-multiversion = "^0.2.4"
sphinx-rtd-theme = "^3.0.2"
sphinxcontrib-plantuml = "^0.30"
ghp-import = "^2.1.0"
black = "^25.1.0"
isort = "^6.0.1"
pycodestyle = "^2.13.0"
flake8 = "^7.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."module"]
"dw-core" = "dw_core"
